from app.extensions import db
from datetime import datetime

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    reserved = db.Column(db.Boolean)
    gem_type = db.Column(db.String(200), nullable=False)
    item_type = db.Column(db.String(200), nullable=False)
    color = db.Column(db.String(200), nullable=False)
    transparency = db.Column(db.String(200), nullable=False)
    shape = db.Column(db.String(200), nullable=False)
    weight = db.Column(db.String(200), nullable=False)
    origin = db.Column(db.String(200), nullable=False)
    price = db.Column(db.String(200), nullable=False)
    description = db.Column(db.Text, nullable=False)
    img = db.Column(db.Text, nullable=False)
    created_user_id = db.Column(db.Integer, nullable=False)
    item_code = db.Column(db.Integer, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime)

class Auction_post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    db.Column(db.Boolean)
    gem_type = db.Column(db.String(200), nullable=False)
    item_type = db.Column(db.String(200), nullable=False)
    color = db.Column(db.String(200), nullable=False)
    transparency = db.Column(db.String(200), nullable=False)
    shape = db.Column(db.String(200), nullable=False)
    weight = db.Column(db.String(200), nullable=False)
    origin = db.Column(db.String(200), nullable=False)
    price = db.Column(db.String(200), nullable=False)
    description = db.Column(db.Text, nullable=False)
    img = db.Column(db.Text, nullable=False)
    auction_price = db.Column(db.Text, nullable=False)
    winner_id = db.Column(db.Integer)
    created_user_id = db.Column(db.Integer, nullable=False)
    item_code = db.Column(db.Integer, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime)
    email_done = db.Column(db.Boolean)
